version: "3"
services:
  backend:
    image: manasagr2201/backend-image
    container_name: backend-container
    ports:
      - 4000:4000
    networks:
      - my-network

  frontend:
    image: manasagr2201/frontend-image
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - my-network
      
networks:
  my-network:
    driver: bridge
