---
- name: Deploy docker images
  hosts: localhost

  tasks:
    - name: Create new directory
      shell: mkdir -p ~/spe_main_project_ansible
    
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: /var/lib/jenkins/workspace/Dictionary App/docker-compose.yml
        dest: ~/spe_main_project_ansible/docker-compose.yml
        
    - name: Run docker compose
      command: docker compose up -d
      args:
        chdir: ~/spe_main_project_ansible
